# Generated by Django 3.2.8 on 2023-12-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
