# Generated by Django 3.2.8 on 2023-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='booklei',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
    ]
