# Generated by Django 3.2.8 on 2023-12-05 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='名称')),
                ('miaoshu', models.TextField(verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='名称')),
                ('author', models.CharField(max_length=10, null=True, verbose_name='作者')),
                ('publish', models.CharField(max_length=20, null=True, verbose_name='出版社')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='出版时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.booklei', verbose_name='类型')),
            ],
        ),
    ]
