# Generated by Django 3.2.8 on 2023-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20231205_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='upload/cover/abc.png', upload_to='upload/covers', verbose_name='封面'),
        ),
    ]
