# Generated by Django 4.2.8 on 2023-12-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=40, null=True, verbose_name='地点')),
                ('detail_place', models.TextField(verbose_name='详细地点描述')),
            ],
            options={
                'verbose_name': '地点',
                'verbose_name_plural': '地点',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='名字')),
                ('password', models.CharField(max_length=40, null=True, verbose_name='密码')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smallshop.place', verbose_name='地点')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='商品名称')),
                ('prime_cost', models.CharField(max_length=40, null=True, verbose_name='进货价格')),
                ('price', models.CharField(max_length=40, null=True, verbose_name='价格')),
                ('quantity', models.CharField(max_length=40, null=True, verbose_name='数量')),
                ('residual_quantity', models.CharField(max_length=40, null=True, verbose_name='剩余数量')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smallshop.place', verbose_name='商品地点')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
