# Generated by Django 4.2.8 on 2023-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prime_cost',
            field=models.FloatField(null=True, verbose_name='进货价格'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='residual_quantity',
            field=models.FloatField(null=True, verbose_name='剩余数量'),
        ),
    ]
