# Generated by Django 4.2.8 on 2023-12-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallshop', '0002_alter_shop_price_alter_shop_prime_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='residual_quantity',
            field=models.IntegerField(null=True, verbose_name='剩余数量'),
        ),
    ]
