# Generated by Django 3.2.8 on 2023-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallshop', '0003_alter_shop_quantity_alter_shop_residual_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='msg',
            field=models.ImageField(default='upload/covers/abc.png', upload_to='upload/covers', verbose_name='商品图片'),
        ),
    ]
